controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Projects;
use app\models\search\ProjectsSearch;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\helpers\Json;

class SiteController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionExport()
    {




           $projects = Projects::find()->asArray()->all();



             foreach($projects as $key => $project)
              {
                  $celData = [
                      0 => [
                          [
                              'id',
                              'title',
                              'description',
                              'organization',
                              'start',
                              'end'

                          ],

                      ]
                  ];

                 if($key == 0)
                 {
                     $cellData[$key+1] = [


                         0 => $project->id,
                         1 => $project->title,
                         2 => $project->description,
                         3 => $project->organization,


                         4 => $project->start,
                         5 => $project->end,

                        /*
                         6 => $project->role,
                         7 => $project->link,
                         8 => $project->skills,
                         9 => $project->attachments,
                         10 => $project->type,
                         11 => $project->active,
                         12 => $project->sort,
                         13 => $project->updated_at,
                         14 => $project->created_at
                         */


                     ];


                 }

                 else

                     {
                         $cellData[$key] = [


                             0 => $project->id,
                             1 => $project->title,
                             2 => $project->description,
                             3 => $project->organization,


                             4 => $project->start,
                             5 => $project->end,


                             /*
                             6 => $project->role,
                             7 => $project->link,
                             8 => $project->skills,
                             9 => $project->attachments,
                             10 => $project->type,
                             11 => $project->active,
                             12 => $project->sort,
                             13 => $project->updated_at,
                             14 => $project->created_at
                             */

                         ];
                     }
                  }



        Yii::$app->excel->write($cellData);
        Yii::$app->excel->store('projects', 'xls', './docs/excel/');
        $this->redirect('/docs/excel/projects.xls');
    }


    public function actionImage()
    {

         $model = new Projects();
         $someFiles = UploadedFile::getInstances($model, 'attachments');
        $directory = Yii::getAlias('@web/files') . DIRECTORY_SEPARATOR . Yii::$app->session->id . DIRECTORY_SEPARATOR;
        if (!is_dir($directory)) {
            FileHelper::createDirectory($directory);
        }


        if ($someFiles) {

            foreach($someFiles as $someFile)
            {

                $uid = uniqid(time(), true);
                $fileName = $uid . '.' . $someFile->extension;
                $filePath = $directory . $fileName;
                if ($someFile->saveAs($filePath)) {
                    $path = '/images/projects/' . Yii::$app->session->id . DIRECTORY_SEPARATOR . $fileName;
                    return Json::encode([
                        'files' => [
                            [
                                'name' => $fileName,
                                'size' => $someFile->size,
                                'url' => $path,
                                'thumbnailUrl' => $path,
                                'deleteUrl' => 'image-delete?name=' . $fileName,
                                'deleteType' => 'POST',
                            ],
                        ],
                    ]);
                }
            }


        }

        return '';





    }


    public function actionUpload()
    {
        $transData  = [];

        $model = new ProjectsSearch();
        $importFile = UploadedFile::getInstance($model, 'xml_file');
        $rawDatas = Yii::$app->excel->read($importFile->tempName);
        $ids = [];
        foreach($rawDatas as  $sheetName => $rawData)
        {
          foreach($rawData as $raw)
          {
              $id = (int)$raw[0];
              $ids[] = $id;
              $isset = Projects::findOne($id);
              if(!$isset)
              {

                  if(!empty($id) && is_integer($id) )
                  {



                      $modelProject = new Projects([
                          'id' => $id,
                          'title' => $raw[1],
                          'description' => $raw[2],
                          'organization' => $raw[3],
                          'start' => $raw[4],
                          'end' => $raw[5],
                          'role' => $raw[6],
                          'link' => $raw[7],
                          'skills' => $raw[8],
                          'attachments' => $raw[9],
                          'type' => $raw[10],
                          'active' => $raw[11],
                          'sort' => $raw[12],
                          'updated_at' => $raw[13],
                          'created_at' => $raw[14],

                      ]);

                      $modelProject->save(false);
                  }

              }

              else
                  {

                     $isset->title = $raw[1];
                     $isset->description = $raw[2];
                      $isset->organization = $raw[3];
                      $isset->start = $raw[4];
                      $isset->end = $raw[5];
                      $isset->role = $raw[6];
                      $isset->link = $raw[7];
                      $isset->skills = $raw[8];
                      $isset->attachments = $raw[9];
                      $isset->type = $raw[10];
                      $isset->active = $raw[11];
                      $isset->sort = $raw[12];
                      $isset->updated_at = $raw[13];
                      $isset->created_at = $raw[14];

                      $isset->save(false);

                      $projects = Projects::find()->asArray()->all();









                  }

          }

        }

        $projects = Projects::find()->all();
        foreach($projects as $project)
        {
           if(!in_array($project->id, $ids))
           {
               $project->delete();
           }

        }

    }
    
    
    public function actionIndex()
    {
        $searchModel = new ProjectsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        $model = new Projects();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }


    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    protected function findModel($id)
    {
        if (($model = Projects::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use kartik\select2\Select2;
use app\models\Skills;
use yii\helpers\ArrayHelper;
use dosamigos\fileupload\FileUploadUI;
use yii\helpers\Json;

?>

<div class="projects-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'organization')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'start')->widget(
        DatePicker::className(), [


        'clientOptions' => [
            'autoclose' => true,
            'format' => 'dd.mm.yyyy'
        ]
    ]);?>

    <?= $form->field($model, 'end')->widget(
        DatePicker::className(), [
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'dd.mm.yyyy'
        ]
    ]);?>


    <?= $form->field($model, 'role')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'link')->textInput(['maxlength' => true]) ?>


    <?=
     $form->field($model, 'skills[]')->widget(Select2::classname(), [

        'data' => ArrayHelper::map(Skills::find()->all(), 'id', 'title'),

        'language' => 'en',
        'options' => [
                'value' => Json::decode($model->skills, true),
                'placeholder' => 'Select skills ...',
                'multiple' => true,

        ],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>

    <?= FileUploadUI::widget([
        'model' => $model,
        'attribute' => 'attachments',
        'options' => ['accept' => 'image/*, .xls, .xlsx, .doc, .docx, .pdf, .txt'],
        'url' => ['site/image'],
        'gallery' => false,
        'clientOptions' => [
            'maxFileSize' => 2000000
        ],
        // ...
        'clientEvents' => [
            'fileuploaddone' => 'function(e, data) {
                            
                                console.log(data);
                            }',
            'fileuploadfail' => 'function(e, data) {
                              
                                console.log(data);
                            }',
        ],
    ]); ?>

    <?= $form->field($model, 'type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'active')->textInput() ?>

    <?= $form->field($model, 'sort')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = 'Create Projects';
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use dosamigos\fileupload\FileUpload;
use kartik\select2\Select2;

$this->title = 'Projects';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-index">
<div class="row form-group">
    <div class="col-sm-4 form-group">
        <?= Html::a('Create Projects', ['create'], ['class' => 'btn btn-success']) ?>
    </div>

    <div class="col-sm-4 form-group">
        <?= Html::a('Export to Excel', [''], ['class' => 'btn btn-success', 'id' => 'excel_export']) ?>
    </div>
    <div class="col-sm-4 form-group">
        <?= FileUpload::widget([
            'model' => $searchModel,
            'attribute' => 'xml_file',
            'url' => ['site/upload'], // your url, this is just for demo purposes,
            'options' => ['accept' => 'xml/*'],
            'clientOptions' => [
                'maxFileSize' => 2000000
            ],
            // Also, you can specify jQuery-File-Upload events
            // see: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#processing-callback-options
            'clientEvents' => [
                'fileuploaddone' => 'function(e, data) {
                                 $.pjax.reload({container: "#updateProject"});
                                 alert("Excel file loaded! Projects was updated!");
                                
                            }',
                'fileuploadfail' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
            ],
        ]); ?>
    </div>
</div>




    <?php Pjax::begin(['id' => 'updateProject']); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'description:ntext',
            'organization',
            'start',
            //'end',
            //'role',
            //'link',
            //'skills:ntext',
            //'attachments:ntext',
            //'type',
            //'active',
            //'sort',
            //'updated_at',
            //'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>




</div>


<?
$script = '
            $(document).ready(function(){
            $("#excel_export").click(function(e)
            {
                e.preventDefault();
                $.ajax({
                url: "/site/export",
                method: "GET",
                success: function(response)
                {
                  console.log(response);
                }
                
                
                });
        
        
            });


         });
        
        ';

     $this->registerJs($script);
?>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/project.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Projects';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = 'Update Projects: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="projects-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/site/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="projects-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'description:ntext',
            'organization',
            'start',
            'end',
            'role',
            'link',
            'skills:ntext',
            'attachments:ntext',
            'type',
            'active',
            'sort',
            'updated_at',
            'created_at',
        ],
    ]) ?>

</div>